language: node_js

matrix:
  include:
      - node_js: node
        env:  NODE_ENVIRONMENT=development BUILD_STEPS='compile test'
        os: linux
      - node_js: node
        env:  NODE_ENVIRONMENT=development BUILD_STEPS='compile test'
        os: osx
      - node_js: 10
        env:  NODE_ENVIRONMENT=production  BUILD_STEPS='compile test'
        os: linux
      - node_js: 10
        env:  NODE_ENVIRONMENT=production  BUILD_STEPS='compile test'
        os: osx
      - node_js: 8
        env:  NODE_ENVIRONMENT=production  BUILD_STEPS='compile test'
        os: linux
      - node_js: 8
        env:  NODE_ENVIRONMENT=production  BUILD_STEPS='compile test'
        os: osx
      - node_js: 8
        env:  NODE_ENVIRONMENT=development BUILD_STEPS='compile test'
        os: linux
      - node_js: 8
        env:  NODE_ENVIRONMENT=development BUILD_STEPS='compile test'
        os: osx
      - node_js: 7
        env:  NODE_ENVIRONMENT=production  BUILD_STEPS='compile test'
        os: linux
      - node_js: 7
        env:  NODE_ENVIRONMENT=production  BUILD_STEPS='compile test'
        os: osx
      - node_js: 7
        env:  NODE_ENVIRONMENT=development BUILD_STEPS='compile'
      - node_js: 6
        env:  NODE_ENVIRONMENT=production  BUILD_STEPS='compile test'
      - node_js: 6
        env:  NODE_ENVIRONMENT=development BUILD_STEPS='compile'
      - node_js: 5
        env:  NODE_ENVIRONMENT=production  BUILD_STEPS='compile test'
      - node_js: 5
        env:  NODE_ENVIRONMENT=development BUILD_STEPS='compile'

cache:
  directories:
    - node_modules

script:
  - if [ "${TRAVIS_EVENT_TYPE}" = "cron" ]; then npm run build; fi
  - if [ "${TRAVIS_EVENT_TYPE}" != "cron" ]; then for step in ${BUILD_STEPS}; do echo "*** Running build step $step"; npm run $step; done; fi
